// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/answer/finish/{quizId}": {
            "post": {
                "description": "Finish answering question in quiz.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Answer"
                ],
                "summary": "finish answer quiz",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd refresh token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Quiz Id",
                        "name": "quizId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/answer.Answer"
                        }
                    }
                }
            }
        },
        "/answer/getFinished/{quizId}": {
            "get": {
                "description": "Get finished answer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Answer"
                ],
                "summary": "get finished answer",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Quiz Id",
                        "name": "quizId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/answer.Answer"
                        }
                    }
                }
            }
        },
        "/answer/save": {
            "post": {
                "description": "Adding new answer to the database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Answer"
                ],
                "summary": "save answer",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd refresh token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Answer Data",
                        "name": "AnswerQuestionInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/answer.AnswerQuestionInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/answer.Answer"
                        }
                    }
                }
            }
        },
        "/question/save": {
            "post": {
                "description": "Adding new questions to the database. Add field duration input as string for example \"50 sec\" or \"1 min\", it will converted into second in server and return to client as second also. The client should format it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "save questions",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd refresh token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User Data",
                        "name": "addQuestionInputs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/question.AddQuestionInputs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/question.Question"
                        }
                    }
                }
            }
        },
        "/question/{quizId}": {
            "get": {
                "description": "Get question by each number from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Question"
                ],
                "summary": "get question each number",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd refresh token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Quiz Id",
                        "name": "quizId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/participantQuestion.ParticipantQuestion"
                        }
                    }
                }
            }
        },
        "/quiz/join/{quizCode}": {
            "post": {
                "description": "Joining certain quiz",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quiz"
                ],
                "summary": "join quiz",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd refresh token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Quiz Code",
                        "name": "quizCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quiz.Quiz"
                        }
                    }
                }
            }
        },
        "/quiz/save": {
            "post": {
                "description": "Adding new quiz to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quiz"
                ],
                "summary": "save quiz",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd refresh token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User Data",
                        "name": "createQuizInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/quiz.CreateQuizInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quiz.Quiz"
                        }
                    }
                }
            }
        },
        "/quiz/{id}": {
            "get": {
                "description": "Get quiz from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quiz"
                ],
                "summary": "get quiz detail",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd refresh token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Quiz Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quiz.Quiz"
                        }
                    }
                }
            }
        },
        "/quizCategory": {
            "get": {
                "description": "Get all quiz category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quiz Category"
                ],
                "summary": "get all quiz category",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quizCategory.QuizCategory"
                        }
                    }
                }
            }
        },
        "/quizCategory/save": {
            "post": {
                "description": "Adding new quiz category to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quiz Category"
                ],
                "summary": "save quiz category",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd refresh token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User Data",
                        "name": "quizCategoryInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/quizCategory.QuizCategoryInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quizCategory.QuizCategory"
                        }
                    }
                }
            }
        },
        "/quizCategory/{id}": {
            "get": {
                "description": "Get quiz category by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quiz Category"
                ],
                "summary": "get quiz category by id",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Quiz Category Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quizCategory.QuizCategory"
                        }
                    }
                }
            }
        },
        "/user/changePassword": {
            "post": {
                "description": "Change Password user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "change password",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "changePasswordInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangePasswordUserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenObject"
                        }
                    }
                }
            }
        },
        "/user/googleAuth": {
            "post": {
                "description": "Google Auth",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "google auth",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "googleOAuthInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.GoogleOAuthInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenObject"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Login user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "loginUserInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginUserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenObject"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "description": "Get user profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "get profile",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                }
            }
        },
        "/user/refreshToken": {
            "post": {
                "description": "Refresh JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "refresh token",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd refresh token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "User Data",
                        "name": "refreshTokenInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RefreshTokenInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenObject"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Adding new user to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "register",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "registerUserInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RegisterUserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenObject"
                        }
                    }
                }
            }
        },
        "/user/resetPassword": {
            "post": {
                "description": "Send email consist of OTP to user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "reset password",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "resetPasswordInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ResetPasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenObject"
                        }
                    }
                }
            }
        },
        "/user/validateToken": {
            "get": {
                "description": "Validate JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "validate token",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenObject"
                        }
                    }
                }
            }
        },
        "/user/verifyOtp": {
            "post": {
                "description": "Verify OTP user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Authentication"
                ],
                "summary": "verify otp",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "verifyOtpInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/otp.VerifyOtpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenObject"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "answer.Answer": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "answer_duration": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "generated_suggestion": {
                    "type": "string"
                },
                "grade": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "question": {
                    "$ref": "#/definitions/question.Question"
                },
                "question_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "answer.AnswerQuestionInput": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "answer_duration": {
                    "type": "integer"
                },
                "question_id": {
                    "type": "string"
                }
            }
        },
        "controllers.TokenObject": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "otp.VerifyOtpInput": {
            "type": "object",
            "required": [
                "otp_code"
            ],
            "properties": {
                "otp_code": {
                    "type": "string"
                }
            }
        },
        "participantQuestion.ParticipantQuestion": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "participation_id": {
                    "type": "string"
                },
                "question": {
                    "$ref": "#/definitions/question.Question"
                },
                "question_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "question.AddQuestionInput": {
            "type": "object",
            "required": [
                "duration",
                "grade_percentage",
                "question"
            ],
            "properties": {
                "duration": {
                    "type": "string"
                },
                "grade_percentage": {
                    "type": "number"
                },
                "question": {
                    "type": "string"
                },
                "reference_answer": {
                    "type": "string"
                }
            }
        },
        "question.AddQuestionInputs": {
            "type": "object",
            "required": [
                "questions",
                "quiz_id"
            ],
            "properties": {
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/question.AddQuestionInput"
                    }
                },
                "quiz_id": {
                    "type": "string"
                }
            }
        },
        "question.Question": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "grade_percentage": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "point": {
                    "type": "number"
                },
                "question": {
                    "type": "string"
                },
                "questionImage": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/questionImage.QuestionImage"
                    }
                },
                "quiz_id": {
                    "type": "string"
                },
                "reference_answer": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "questionImage.QuestionImage": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "question_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "quiz.CreateQuizInput": {
            "type": "object",
            "required": [
                "description",
                "quiz_category_id",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "quiz_category_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "quiz.Quiz": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "end_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "question": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/question.Question"
                    }
                },
                "quizCategory": {
                    "$ref": "#/definitions/quizCategory.QuizCategory"
                },
                "quiz_category_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "quizCategory.QuizCategory": {
            "type": "object",
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "quizCategory.QuizCategoryInput": {
            "type": "object",
            "required": [
                "category_name",
                "description"
            ],
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "user.ChangePasswordUserInput": {
            "type": "object",
            "required": [
                "change_password",
                "otp_code",
                "password"
            ],
            "properties": {
                "change_password": {
                    "type": "string"
                },
                "otp_code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.GoogleOAuthInput": {
            "type": "object",
            "required": [
                "oAuthAccessToken"
            ],
            "properties": {
                "oAuthAccessToken": {
                    "type": "string"
                }
            }
        },
        "user.LoginUserInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user.RefreshTokenInput": {
            "type": "object",
            "required": [
                "accessToken"
            ],
            "properties": {
                "accessToken": {
                    "type": "string"
                }
            }
        },
        "user.RegisterUserInput": {
            "type": "object",
            "required": [
                "confirmPassword",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.ResetPasswordInput": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "last_login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
