name: CI/CD for Golang Ajher Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_KEY_FILE }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/ajher-409804/ajher_server:${{ github.sha }} .
          docker tag gcr.io/ajher-409804/ajher_server:${{ github.sha }} gcr.io/ajher-409804/ajher_server:latest
          docker push gcr.io/ajher-409804/ajher_server:${{ github.sha }}
          docker push gcr.io/ajher-409804/ajher_server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_KEY_FILE }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ajher-server \
            --image=gcr.io/ajher-409804/ajher_server:${{ github.sha }} \
            --platform=managed \
            --region=asia-southeast2 \
            --memory=4Gi \
            --allow-unauthenticated \
            --set-env-vars=JWT_SECRET_KEY="${{secrets.JWT_SECRET_KEY}}",OAUTH_CLIENT_ID="${{secrets.OAUTH_CLIENT_ID}}",OAUTH_CLIENT_SECRET="${{secrets.OAUTH_CLIENT_SECRET}}",CONFIG_SMTP_HOST="${{secrets.CONFIG_SMTP_HOST}}",CONFIG_SMTP_PORT="${{secrets.CONFIG_SMTP_PORT}}",CONFIG_SENDER_NAME="${{secrets.CONFIG_SENDER_NAME}}",CONFIG_AUTH_EMAIL="${{secrets.CONFIG_AUTH_EMAIL}}",CONFIG_AUTH_PASSWORD="${{secrets.CONFIG_AUTH_PASSWORD}}",MODEL_SERVICE_URL="${{secrets.MODEL_SERVICE_URL}}",FIRESTORE_PROJECT_ID="${{secrets.FIRESTORE_PROJECT_ID}}",FIREBASE_SERVICE_ACCOUNT_PATH="${{secrets.FIREBASE_SERVICE_ACCOUNT_PATH}}"
